"""Runtime theming for nicegui-shadcn.

A shadcn/ui theme is nothing but a set of CSS custom properties: the design
tokens are declared in a ``:root`` block, the dark variant re-declares the same
names under ``.dark``, and every utility class is a ``var()`` lookup.  Because
the tokens are plain custom properties, a theme can be changed *after* the
stylesheet has been compiled -- which is what this module does.  It appends a
small stylesheet of its own to the page head, after ``static/shadcn.css``, so
whatever is set here wins by source order::

    from nicegui_shadcn import theming

    theming.use_base_color('zinc')
    theming.set_radius(0.75)
    theming.set_colors(primary='#2563eb')
    theming.set_dark_colors(primary='#60a5fa')
    theming.add_color('warning', light='#f59e0b', dark='#fbbf24',
                      foreground_light='#1c1917', foreground_dark='#1c1917')

Four details are worth knowing before reading the implementation.

*Every* function can be called either before ``ui.run()`` (the head block is
``shared``, so it reaches every page) or later at runtime: the injected block
carries a snippet that replaces the stylesheet in every open page, which is what
makes a live theme picker work without a reload.  Calls made before the app
starts are coalesced into one injection at startup, so a setup block that sets
a dozen tokens still ships a single snapshot instead of a dozen.

The utility classes generated by :func:`add_color` are wrapped in
``@layer utilities`` and carry ``!important``.  NiceGUI declares that layer
*before* ``quasar_importants``, and for ``!important`` declarations the layer
order is reversed -- so the wrapper is what lets a custom ``.bg-warning`` beat
Quasar's own ``.bg-warning``.  Token values (which stay unlayered) need no such
trick: unlayered declarations beat layered ones.

:func:`add_color` only generates the plain and ``dark:`` variants of the seven
colour utilities.  The state variants (``hover:``, ``focus:``, ``focus-visible:``,
``active:``, ``disabled:``, ``group-hover:``) that the compiled stylesheet has
for the built-in tokens are deliberately not generated, because that matrix is
large and rarely needed; add the token to your own stylesheet and rebuild if you
need them.  Retheming an existing token with :func:`set_colors` always keeps the
full matrix.

The seven base colours published at ``https://ui.shadcn.com/r/colors/<name>.json``
are bundled in ``static/base-colors.json``; ``tests/update_base_colors.py``
refreshes that asset.
"""

from __future__ import annotations

import asyncio
import difflib
import json
import re
from pathlib import Path
from string import Template
from typing import Any

from nicegui import Client, app, ui

from .elements.base import option

__all__ = [
    'BASE_COLORS',
    'COLOR_TOKENS',
    'add_color',
    'css',
    'current',
    'reset',
    'set_colors',
    'set_dark_colors',
    'set_radius',
    'use_base_color',
]

_BASE_COLORS_PATH = Path(__file__).parent / 'static' / 'base-colors.json'

BASE_COLORS = ('neutral', 'stone', 'zinc', 'mauve', 'olive', 'mist', 'taupe')
'''The base colours shadcn publishes (https://ui.shadcn.com/docs/theming).'''

_BASE_COLOR_CHOICES = {color: color for color in BASE_COLORS}

COLOR_TOKENS = (
    'background', 'foreground',
    'card', 'card-foreground',
    'popover', 'popover-foreground',
    'primary', 'primary-foreground',
    'secondary', 'secondary-foreground',
    'muted', 'muted-foreground',
    'accent', 'accent-foreground',
    'destructive', 'destructive-foreground',
    'border', 'input', 'ring',
    'chart-1', 'chart-2', 'chart-3', 'chart-4', 'chart-5',
    'sidebar', 'sidebar-foreground',
    'sidebar-primary', 'sidebar-primary-foreground',
    'sidebar-accent', 'sidebar-accent-foreground',
    'sidebar-border', 'sidebar-ring',
)
'''Every token :func:`set_colors` accepts, in the order the stylesheet uses.

``destructive-foreground`` is shipped by this package but is no longer part of
shadcn's registry palettes, so :func:`use_base_color` leaves it alone.
'''

_DARK_SELECTOR = 'body.body--dark, .dark'
_DARK_VARIANT = ':where(body.body--dark, body.body--dark *)'
_STYLE_ID = 'nicegui-shadcn-theme'

_FAMILIES = (
    ('bg', 'background-color'),
    ('text', 'color'),
    ('border', 'border-color'),
    ('ring', '--tw-ring-color'),
    ('fill', 'fill'),
    ('stroke', 'stroke'),
    ('outline', 'outline-color'),
)
'''``(utility prefix, CSS property)`` for the colour utilities we can generate.'''

_NAME_RE = re.compile(r'^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$')
_FORBIDDEN = frozenset(';{}<>')

_BODY = Template("""(() => {
  const id = '$style_id';
  document.querySelectorAll('style#' + id).forEach((element) => element.remove());
  const style = document.createElement('style');
  style.id = id;
  style.textContent = $payload;
  document.head.append(style);
})();""")
'''The snippet in both of its shapes: sent over the websocket, or wrapped in a tag.'''

_REPLACE = Template('<script>\n' + _BODY.template + '\n</script>')

_light: dict[str, str] = {}
_dark: dict[str, str] = {}
_radius: str | None = None
_custom: dict[str, dict[str, str | None]] = {}
_pushed: str | None = None
_started = False
_hooked = False
_radius_locked = False
_palettes: dict[str, Any] | None = None


def use_base_color(name: str) -> None:
    """Replace the whole palette with one of shadcn's base colours.

    :param name: one of :data:`BASE_COLORS`, for example ``'zinc'``

    Light and dark tokens are taken verbatim from shadcn's registry, including
    ``chart-1`` … ``chart-5`` (which the registry tints to a monochrome ramp,
    unlike the vivid charts of the default theme).  Overrides made with
    :func:`set_colors` / :func:`set_dark_colors` are discarded; colours added
    with :func:`add_color` are kept.

    The palette's own ``--radius`` is applied as well, unless you have called
    :func:`set_radius` yourself: an explicit radius is never clobbered by a
    later base colour, so a live theme picker keeps the corner radius you chose.
    """
    option('base colour', name, _BASE_COLOR_CHOICES)
    palette = _load_palettes()[name]
    global _radius
    _light.clear()
    _light.update(palette['light'])
    _dark.clear()
    _dark.update(palette['dark'])
    if not _radius_locked:
        _radius = palette['radius']
    _apply()


def set_colors(**tokens: str) -> None:
    """Override individual light-mode tokens.

    Keyword names are the tokens of :data:`COLOR_TOKENS` with underscores
    instead of hyphens: ``set_colors(primary='#2563eb', card_foreground='#111')``.
    Dark mode keeps its own values, so a colour that should follow usually needs
    :func:`set_dark_colors` as well.
    """
    _light.update(_clean(tokens, 'set_colors'))
    _apply()


def set_dark_colors(**tokens: str) -> None:
    """Override individual dark-mode tokens, the counterpart of :func:`set_colors`."""
    _dark.update(_clean(tokens, 'set_dark_colors'))
    _apply()


def set_radius(value: float | str) -> None:
    """Set the ``--radius`` token that every corner of the design derives from.

    :param value: a number of ``rem`` (``0.75``) or an explicit CSS length
        (``'12px'``)

    The stylesheet derives ``sm``/``md``/``lg``/``xl`` from this one value, so
    changing it re-shapes buttons, inputs, cards and popovers together.  Calling
    this locks the radius: a later :func:`use_base_color` keeps it.
    """
    global _radius, _radius_locked
    if isinstance(value, bool) or not isinstance(value, (int, float, str)):
        raise TypeError('set_radius() takes a number of rem or a CSS length string, '
                        f'not {type(value).__name__}')
    _radius = _value(value, 'set_radius()') if isinstance(value, str) else f'{value:g}rem'
    _radius_locked = True
    _apply()


def add_color(name: str,
              light: str,
              dark: str,
              *,
              foreground_light: str | None = None,
              foreground_dark: str | None = None) -> None:
    """Register a colour that shadcn does not ship, and generate its utilities.

    :param name: a kebab-case token name such as ``'warning'``
    :param light: the value for the light theme
    :param dark: the value for the dark theme
    :param foreground_light: optional colour to place *on* the new colour
    :param foreground_dark: same for dark mode; either foreground defaults to
        the other one

    This defines ``--warning`` (and ``--warning-foreground``) and the matching
    ``bg-warning``, ``text-warning``, ``border-warning``, ``ring-warning``,
    ``fill-warning``, ``stroke-warning``, ``outline-warning``, ``divide-warning``
    utilities, plus their ``dark:`` variants::

        theming.add_color('warning', light='#f59e0b', dark='#fbbf24',
                          foreground_light='#1c1917')
        shadcn.badge('Beta').classes('bg-warning text-warning-foreground')
    """
    if not isinstance(name, str) or not _NAME_RE.match(name):
        raise ValueError('add_color() needs a kebab-case name such as "warning", '
                         f'not {name!r}')
    if name in COLOR_TOKENS:
        raise ValueError(f'{name!r} is one of the built-in tokens; '
                         f'use set_colors({name.replace("-", "_")}=...) instead')
    foreground_light = _value(foreground_light, 'add_color(foreground_light=...)') \
        if foreground_light is not None else None
    foreground_dark = _value(foreground_dark, 'add_color(foreground_dark=...)') \
        if foreground_dark is not None else None
    if foreground_light is not None and foreground_dark is None:
        foreground_dark = foreground_light
    elif foreground_dark is not None and foreground_light is None:
        foreground_light = foreground_dark
    _custom[name] = {
        'light': _value(light, f'add_color({name!r}, light=...)'),
        'dark': _value(dark, f'add_color({name!r}, dark=...)'),
        'foreground_light': foreground_light,
        'foreground_dark': foreground_dark,
    }
    _apply()


def reset() -> None:
    """Drop every override and fall back to the palette compiled into the stylesheet."""
    global _radius, _radius_locked
    _light.clear()
    _dark.clear()
    _custom.clear()
    _radius = None
    _radius_locked = False
    _apply()


def current() -> dict[str, Any]:
    """Return the current theme as plain data, for tests or a settings page."""
    return {
        'radius': _radius,
        'light': dict(_light),
        'dark': dict(_dark),
        'colors': {name: dict(spec) for name, spec in sorted(_custom.items())},
    }


def css() -> str:
    """Return the stylesheet for the current theme, or ``''`` when nothing is set.

    Useful to inspect what gets injected, or to write a theme to a file and
    serve it as a real stylesheet instead of relying on the runtime injection.
    """
    light = _ordered(_tokens('light'))
    dark = _ordered(_tokens('dark'))
    if not light and not dark and _radius is None:
        return ''
    blocks = ['/* nicegui-shadcn theme - generated by nicegui_shadcn.theming */']
    root: dict[str, str] = {}
    if _radius is not None:
        root['radius'] = _radius
    root.update(light)
    if root:
        blocks.append(_rule(':root', root))
    if dark:
        blocks.append(_rule(_DARK_SELECTOR, dark))
    utilities = _utility_rules()
    if utilities:
        blocks.append('@layer utilities {\n' + '\n'.join(utilities) + '\n}')
    return '\n\n'.join(blocks) + '\n'


def _apply() -> None:
    """Refresh the injected stylesheet, or queue it for the startup flush.

    Before the app starts, changes are coalesced: only the last snapshot is
    pushed, once, when NiceGUI's startup handlers run.  Afterwards every change
    is pushed straight away and replayed in the pages that are already open, so
    a live theme picker updates without a reload.
    """
    if not _started:
        _hook()
        return
    if _push():
        _broadcast(_pushed or '')


def _hook() -> None:
    """Register the one-shot flush for the moment NiceGUI starts serving."""
    global _hooked
    if _hooked:
        return
    _hooked = True
    app.on_startup(_flush)


def _flush() -> None:
    """Push the theme that was accumulated before the app started."""
    global _started
    _started = True
    _push()


def _push() -> bool:
    """Append the current stylesheet to the page head, unless it is already there.

    The block is ``shared``, so it is part of the HTML of every page from now on
    and is applied during parsing -- before the first paint, hence no flash.
    """
    global _pushed
    payload = css()
    if payload == _pushed:
        return False
    if not payload and _pushed is None:
        return False  # nothing was ever themed, so there is nothing to clear
    _pushed = payload
    ui.add_head_html(_script(payload), shared=True)
    return True


def _script(payload: str) -> str:
    """The snippet that swaps the stylesheet of a page that is already open."""
    return _REPLACE.substitute(style_id=_STYLE_ID, payload=json.dumps(payload))


def _broadcast(payload: str) -> None:
    """Replay the swapping snippet in every page that is already connected.

    The shared head block only reaches pages that are rendered *after* the
    change, so open pages need the snippet sent over their websocket instead.
    ``run_javascript`` takes bare JavaScript, so the ``<script>`` wrapper that
    the head injection needs is left off here.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return  # no loop, so no open page: the next page load picks the theme up
    code = _BODY.substitute(style_id=_STYLE_ID, payload=json.dumps(payload))
    for client in list(Client.instances.values()):
        if client.has_socket_connection:
            client.run_javascript(code)


def _rule(selector: str, tokens: dict[str, str]) -> str:
    body = '\n'.join(f'  --{name}: {value};' for name, value in tokens.items())
    return f'{selector} {{\n{body}\n}}'


def _tokens(mode: str) -> dict[str, str]:
    """Collect the tokens of one mode, including the colours added at runtime."""
    tokens = dict(_light if mode == 'light' else _dark)
    for name, spec in _custom.items():
        value = spec[mode]
        if value is not None:
            tokens[name] = value
        foreground = spec[f'foreground_{mode}']
        if foreground is not None:
            tokens[f'{name}-foreground'] = foreground
    return tokens


def _ordered(tokens: dict[str, str]) -> dict[str, str]:
    known = [name for name in COLOR_TOKENS if name in tokens]
    extra = sorted(name for name in tokens if name not in COLOR_TOKENS)
    return {name: tokens[name] for name in known + extra}


def _utility_rules() -> list[str]:
    rules: list[str] = []
    for name in sorted(_custom):
        tokens = [name]
        spec = _custom[name]
        if spec['foreground_light'] is not None or spec['foreground_dark'] is not None:
            tokens.append(f'{name}-foreground')
        for token in tokens:
            for prefix, prop in _FAMILIES:
                rules.append(f'  .{prefix}-{token} {{ {prop}: var(--{token}) !important; }}')
            rules.append(f'  :where(.divide-{token} > :not(:last-child)) '
                         f'{{ border-color: var(--{token}) !important; }}')
            for prefix, prop in _FAMILIES:
                rules.append(f'  .dark\\:{prefix}-{token}{_DARK_VARIANT} '
                             f'{{ {prop}: var(--{token}) !important; }}')
    return rules


def _load_palettes() -> dict[str, Any]:
    global _palettes
    if _palettes is None:
        data = json.loads(_BASE_COLORS_PATH.read_text(encoding='utf-8'))
        _palettes = data['colors']
    return _palettes


def _clean(tokens: dict[str, str], where: str) -> dict[str, str]:
    return {_token_name(key, where): _value(value, f'{where}({key}=...)')
            for key, value in tokens.items()}


def _token_name(key: str, where: str) -> str:
    name = key.strip().replace('_', '-').lower()
    if name not in COLOR_TOKENS:
        close = difflib.get_close_matches(name, COLOR_TOKENS, n=3, cutoff=0.6)
        hint = ' Did you mean ' + ' or '.join(repr(match) for match in close) + '?' if close else ''
        raise ValueError(f'{where}() got an unknown colour token {key!r}.{hint} '
                         'See nicegui_shadcn.theming.COLOR_TOKENS for the full list.')
    return name


def _value(value: object, where: str) -> str:
    if not isinstance(value, str):
        raise TypeError(f'{where} must be a CSS colour string, not {type(value).__name__}')
    text = value.strip()
    if not text:
        raise ValueError(f'{where} must not be empty')
    bad = ''.join(sorted(set(text) & _FORBIDDEN))
    if bad:
        raise ValueError(f'{where} must not contain {bad!r}: the value is injected into '
                         'a <style> element')
    return text
