"""Regenerate ``nicegui_shadcn/static/base-colors.json``.

The seven base colour palettes are published by shadcn as a registry endpoint
(``https://ui.shadcn.com/r/colors/<name>.json``).  Each one carries the same
palette in three shapes; we want ``cssVarsV4``, which is the ``oklch()`` form
matching the token block in ``frontend/tailwind.css``.

This is a maintenance script, not part of the test suite: it needs network
access.  Run it after shadcn changes a palette, then rebuild and re-run the
tests::

    python tests/update_base_colors.py            # refresh the asset
    python tests/update_base_colors.py --check    # validate what is on disk
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / 'nicegui_shadcn' / 'static' / 'base-colors.json'

REGISTRY = 'https://ui.shadcn.com/r/colors/{name}.json'

BASE_COLORS = ('neutral', 'stone', 'zinc', 'mauve', 'olive', 'mist', 'taupe')
'''The base colours advertised by https://ui.shadcn.com/docs/theming.'''

TOKEN_ORDER = (
    'background', 'foreground',
    'card', 'card-foreground',
    'popover', 'popover-foreground',
    'primary', 'primary-foreground',
    'secondary', 'secondary-foreground',
    'muted', 'muted-foreground',
    'accent', 'accent-foreground',
    'destructive', 'destructive-foreground',
    'border', 'input', 'ring',
    'chart-1', 'chart-2', 'chart-3', 'chart-4', 'chart-5',
    'sidebar', 'sidebar-foreground',
    'sidebar-primary', 'sidebar-primary-foreground',
    'sidebar-accent', 'sidebar-accent-foreground',
    'sidebar-border', 'sidebar-ring',
)
'''Canonical ordering, so that refreshing the asset produces a readable diff.

``destructive-foreground`` is in the list because this package ships the token;
shadcn's current registry no longer emits it, so the palettes simply omit it.
'''


def _ordered(tokens: dict[str, str]) -> dict[str, str]:
    known = [name for name in TOKEN_ORDER if name in tokens]
    extra = sorted(name for name in tokens if name not in TOKEN_ORDER)
    if extra:
        print(f'  note: tokens outside the canonical order are kept at the end: {extra}')
    return {name: tokens[name] for name in known + extra}


def fetch(name: str) -> dict[str, object]:
    """Return one base colour as ``{'radius': ..., 'light': {...}, 'dark': {...}}``."""
    with urllib.request.urlopen(REGISTRY.format(name=name), timeout=30) as response:  # noqa: S310
        payload = json.load(response)
    try:
        v4 = payload['cssVarsV4']
        light = dict(v4['light'])
        dark = dict(v4['dark'])
    except (KeyError, TypeError) as exc:
        raise SystemExit(f'{name}: unexpected registry payload ({exc})') from exc

    radius = light.pop('radius', None)
    if radius is None:
        raise SystemExit(f'{name}: the registry payload has no radius token')
    if 'radius' in dark:
        raise SystemExit(f'{name}: radius is unexpectedly defined in the dark block too')
    return {'radius': radius, 'light': _ordered(light), 'dark': _ordered(dark)}


def build() -> dict[str, object]:
    colors = {}
    for name in BASE_COLORS:
        print(f'fetching {name} ...')
        colors[name] = fetch(name)
        print(f'  radius={colors[name]["radius"]} '
              f'light={len(colors[name]["light"])} dark={len(colors[name]["dark"])}')
    return {
        '$comment': (
            'Generated by tests/update_base_colors.py from '
            + REGISTRY.format(name='<name>')
            + ' (the cssVarsV4 block). Do not edit by hand.'
        ),
        'colors': colors,
    }


def check(path: Path) -> int:
    """Validate the shape of an existing asset without touching the network."""
    if not path.is_file():
        print(f'FAIL {path} does not exist')
        return 1
    data = json.loads(path.read_text(encoding='utf-8'))
    colors = data.get('colors', {})
    problems = []
    missing = [name for name in BASE_COLORS if name not in colors]
    if missing:
        problems.append(f'missing base colours: {missing}')
    reference: tuple[list[str], list[str]] | None = None
    for name, entry in colors.items():
        light, dark = sorted(entry.get('light', {})), sorted(entry.get('dark', {}))
        if not entry.get('radius'):
            problems.append(f'{name}: no radius')
        if not light or not dark:
            problems.append(f'{name}: empty light/dark palette')
        if reference is None:
            reference = (light, dark)
        elif (light, dark) != reference:
            problems.append(f'{name}: token set differs from {BASE_COLORS[0]}')
        for mode, palette in (('light', light), ('dark', dark)):
            for token in palette:
                if not isinstance(entry[mode][token], str):
                    problems.append(f'{name}.{mode}.{token}: not a string')
    if reference is not None:
        print(f'{len(colors)} base colours, {len(reference[0])} light / '
              f'{len(reference[1])} dark tokens each')
    if problems:
        for problem in problems:
            print(f'FAIL {problem}')
        return 1
    print(f'OK {path.relative_to(ROOT)}')
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='validate the existing asset instead of refreshing it')
    args = parser.parse_args()
    if args.check:
        return check(TARGET)

    data = build()
    TARGET.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
    print(f'wrote {TARGET.relative_to(ROOT)} ({TARGET.stat().st_size} bytes)')
    return check(TARGET)


if __name__ == '__main__':
    sys.exit(main())
